# Reference(s): 
# - https://github.com/docker/awesome-compose
# - https://docs.docker.com/go/compose-spec-reference/
version: "3.8"
services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
  db: 
    image: postgres:latest
    container_name: star-infinity-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: star_infinity
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data

